FROM python:3.9 as requirements-stage

WORKDIR /tmp

RUN python -m pip install --upgrade pip
RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.9

WORKDIR /code

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install gdown

# Fac + Lin adapter
RUN bash prep_dirs.sh
RUN gdown https://drive.google.com/drive/folders/12mfLpYq4BTwdbLZnQsdwDJKubM9aOr9f -O /pretrained_models --folder

# RUN bash get_open_entity.sh

# RUN bash prep_litwd.sh

# COPY . /code/
